flask:
  image:
    repository: your/flask-app
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5000

postgresql:
  enabled: true
  postgresUser: user
  postgresPassword: password
  postgresDatabase: mydatabase
